/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Connexion.java
 *
 * Created on 18 déc. 2011, 19:27:42
 */
package tg.ucaouut.projet1.legede.ui;

import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tg.ucaouut.projet1.legede.client.Client;
import tg.ucaouut.projet1.legede.client.Service;
import tg.ucaouut.projet1.legede.service.interfaces.InterServeur;

/**
 *
 * @author bytespoir
 */
public class Connexion extends javax.swing.JFrame {

    Service service;
    private boolean state = false;

    /** Creates new form Connexion */
    public Connexion(Service service) {
        initComponents();
        this.service = service;
    }

    public Connexion() {
        initComponents();

    }

    public boolean isState() {
        return state;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JTextField();
        login = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Password");

        jLabel4.setText("Login:");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jButton2.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(41, 41, 41)
                .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(67, 67, 67)
                .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        boolean t = false;

        try {
            service.startClient();
            t = true;
        }catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "connexion impossible,verifiez votre connectivite au reseau");
            //Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (t) {
            if (service.connectServer(login.getText(), password.getText())) {
                state = true;
                MessageUI message = new MessageUI(service);
                service.getClient().setMsgUI(message);
                message.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "informations de connexion incorrectes");
            }
        }


        //        try {
//            // TODO add your handling code here:
//            
//            String message= "Abalo";
//            //String password= "nini";
//            
//            Client client= new Client();
//            InterServeur serveur = client.getServeurObject();
//            boolean con= serveur.getConnexion(login.getText(),password.getText(), client) ;
//            if(con==true){
//                MessageUI mess= new MessageUI();
//                mess.setVisible(true);
//            }else{
//                JOptionPane.showMessageDialog(this, "L'un de vos données est erronées","Erreur", JOptionPane.ERROR_MESSAGE);
//            }
//            
//            //client.receiveMessage(message, serveur);
//            
//             /*public boolean getConnexion(String login, String password, Object user) throws RemoteException {
//            
//            boolean b=ldapTemplate.authenticate("", "(uid="+login+")", password);
//            if(b){
//                userOnLine.put(user, dao.findByPrimaryKey(login));
//            }
//            
//            return b;*/
//        } catch (RemoteException ex) {
//            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Connexion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField login;
    private javax.swing.JButton ok;
    private javax.swing.JTextField password;
    // End of variables declaration//GEN-END:variables
}
